# Makefile.am in example/tests
# included non-recursively from toplevel directory

if P4EST_ENABLE_BUILD_3D

## Define the program to build. It will be installed in the bin directory.
bin_PROGRAMS += example/tests/working

## Define the source file for the 'working' program.
## The name format follows the convention <directory>_<program>_SOURCES.
example_tests_working_SOURCES = example/tests/working.c

endif